export default function LandingPage({ onGetStarted, onSignIn, onLegal }) {
  return (
    <div className="landing">

      {/* Background decorations */}
      <div className="landing-bg-grid" />
      <div className="landing-orb landing-orb-1" />
      <div className="landing-orb landing-orb-2" />
      <div className="landing-orb landing-orb-3" />

      {/* Nav */}
      <nav className="landing-nav">
        <span className="landing-nav-logo">Echo</span>
        <div className="landing-nav-links">
          <button className="landing-nav-signin" onClick={onSignIn}>Sign In</button>
          <button className="landing-nav-cta" onClick={onGetStarted}>Get Started Free</button>
        </div>
      </nav>

      {/* Hero */}
      <section className="landing-hero">
        <div className="landing-hero-badge">AI-Powered Meeting Intelligence</div>
        <h1 className="landing-hero-title">
          Every meeting,<br />
          <span className="landing-hero-accent">perfectly remembered.</span>
        </h1>
        <p className="landing-hero-sub">
          Echo transcribes your meetings, identifies every speaker, generates AI summaries,
          and lets you chat with your conversation history — all in one place.
        </p>
        <div className="landing-hero-actions">
          <button className="landing-btn-primary" onClick={onGetStarted}>Start for free</button>
          <button className="landing-btn-ghost" onClick={onSignIn}>Sign in</button>
        </div>
        <p className="landing-hero-note">No credit card required.</p>
      </section>

      {/* Features */}
      <section className="landing-features">
        <h2 className="landing-section-title">Everything you need from a meeting</h2>
        <div className="landing-features-grid">
          <div className="landing-feature-card">
            <div className="landing-feature-icon">🎙️</div>
            <h3>Auto Transcription</h3>
            <p>Upload any audio or video and get a word-accurate transcript in minutes, powered by Deepgram.</p>
          </div>
          <div className="landing-feature-card">
            <div className="landing-feature-icon">👥</div>
            <h3>Speaker Identification</h3>
            <p>Echo automatically separates speakers and lets you assign names so the transcript is always clear.</p>
          </div>
          <div className="landing-feature-card">
            <div className="landing-feature-icon">✨</div>
            <h3>AI Summaries</h3>
            <p>Get a concise summary of key decisions, action items, and takeaways — generated by Claude AI.</p>
          </div>
          <div className="landing-feature-card">
            <div className="landing-feature-icon">💬</div>
            <h3>Chat With Your Meetings</h3>
            <p>Ask any question about a meeting and get an instant answer, grounded in the actual transcript.</p>
          </div>
          <div className="landing-feature-card">
            <div className="landing-feature-icon">🔍</div>
            <h3>Searchable Archive</h3>
            <p>All your meetings are indexed and searchable. Find any conversation, decision, or name in seconds.</p>
          </div>
          <div className="landing-feature-card">
            <div className="landing-feature-icon">📝</div>
            <h3>Editable Notes</h3>
            <p>Add your own notes alongside the transcript and summary so everything lives in one document.</p>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="landing-how">
        <h2 className="landing-section-title">Up and running in three steps</h2>
        <div className="landing-steps">
          <div className="landing-step">
            <div className="landing-step-num">1</div>
            <h3>Upload your meeting</h3>
            <p>Drag in an audio or video file. Echo accepts any common format.</p>
          </div>
          <div className="landing-step-arrow">→</div>
          <div className="landing-step">
            <div className="landing-step-num">2</div>
            <h3>We transcribe it</h3>
            <p>Deepgram processes the audio and Echo identifies each speaker automatically.</p>
          </div>
          <div className="landing-step-arrow">→</div>
          <div className="landing-step">
            <div className="landing-step-num">3</div>
            <h3>Ask anything</h3>
            <p>Read the summary, browse the transcript, or chat with Claude about the meeting.</p>
          </div>
        </div>
      </section>

      {/* CTA banner */}
      <section className="landing-cta-banner">
        <h2>Ready to stop forgetting meetings?</h2>
        <p>Join Echo and turn every conversation into a searchable, queryable asset.</p>
        <button className="landing-btn-primary" onClick={onGetStarted}>Create your free account</button>
      </section>

      {/* Footer */}
      <footer className="landing-footer">
        <span className="landing-footer-logo">Echo</span>
        <span className="landing-footer-copy">© {new Date().getFullYear()} Echo. All rights reserved.</span>
        <div className="landing-footer-links">
          <button className="footer-link" onClick={() => onLegal('tos')}>Terms of Service</button>
          <button className="footer-link" onClick={() => onLegal('privacy')}>Privacy Policy</button>
        </div>
      </footer>
    </div>
  )
}
